# Generated by Django 5.2 on 2025-05-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='Price',
            field=models.IntegerField(default=60),
        ),
    ]
